### PR TITLE
Add support link

### LINKED ISSUE #48: Add support me section
Ad link to https://www.buymeacoffee.com/michal.codes

### PR DESCRIPTION
**Pull request by ShatilKhan**
# Pull Request Type
[X] New feature
[] Bug fix

**This PR closes #48 **

# 👨‍💻 Describe your changes

Added the link to the Nav bar

# ✔️ Check List (Check all the applicable boxes)

- [X] I tested my code
- [X] The title and description of the PR is clear and explains what has been done.

# Additional notes

# 📷 Screenshots

### CODE REVIEW

**Comment by ShatilKhan** [comment]
@mslepko , please review
There may be some issues. I'll try to fix everything up soon

**Comment by mslepko** [comment]
> @mslepko , please review There may be some issues. I'll try to fix everything up soon

Thanks, looks great. Can you move it to the bottom, please?

Screenshot 2023-10-02 at 09 49 09

**Comment by ShatilKhan** [comment]
I'm taking a look into it @mslepko

**Comment by ShatilKhan** [comment]
@mslepko please check & let me know

**Pull request merged**
